### ISSUE TITLE
Write an ADR about naming convention of repository with components in MF

### ISSUE THREAD

**Issue by myadryshnikova** [TourmalineCore/inner-circle-documentation#9]

**Comment by akovylyaeva** [comment]
we searched, thought and found nothing more suitable than *inner-circle-layout-ui*
even if there is something, it does not reflect the main essence of the repository, but is something very generalized, as if even a comparison in the form of an adr here does not make sense to write

an example of other options, but they are very generalized
inner-circle-mfe-ui
inner-circle-shared-modules-ui
inner-circle-shared-ui
inner-circle-reusable-ui
inner-circle-universal-ui
inner-circle-shell-ui
inner-circle-pack-ui

by generalization I mean that if we later add some other component that we want to put in a separate repo, then confusion will begin

you can also throw in a bunch of different name options, but they will be terribly long, which is also not cool
